package java_swing;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java_swing.button_action_listener_demo.button_demo;

public class App {

    public static void main(String[] args)
    {
        demo_selection("Button action listener demo");
    }


    public static void demo_selection(String demo_selected)
    {
        switch(demo_selected)
        {
            case "Button action listener demo":
                button_demo demo = new button_demo();
                break;
            default:
                System.out.println("No demo selected");
        }
    }
}
